apiVersion: v1
kind: Service
metadata:
  name: {{ include "zookeeper.fullname" . }}
  labels:
    {{- include "zookeeper.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: zookeeper
      protocol: TCP
      name: zookeeper
  selector:
    {{- include "zookeeper.selectorLabels" . | nindent 4 }}










