{{- if not .Values.admin.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grafana.fullname" . }}-admin
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.admin.userKey }}: {{ .Values.admin.username | b64enc }}
  {{ .Values.admin.passwordKey }}: {{ .Values.admin.password | b64enc }}
{{- end }}


